# This is a basic workflow to help you get started with Actions

name: Deploy test Perseus

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      #Setup node
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: "16.3"
      #Setup ionic cli
      - name: Install Ionic CLI
        run: npm install -g @ionic/cli
      #Install dependecies
      - name: Install deps
        run: npm install
        working-directory: myApp
      #build
      - name: Build app ionic
        run: ionic build --prod --service-worker
        working-directory: myApp
      #Deploy to Github pages
      - name: Deploy Github Pages
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          build_dir: dist/
        env:
          GITHUB_TOKE: ${{secrets.GITHUB_TOKEN}}
